### ISSUE TITLE
Ordering a list of numbers

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#11]
I would like to provide you with a different task, before we move to more mathematical areas. I hope, it's OK for you. 

The task is about ordering a list of numbers. It is complex, but i give you a free hand how to solve it. Only have some requirements:
* create an array with 100 numbers, randomly organized
* use a known algorithm to order this array
* in the end, give me a basic comparison of the run times, each algorithm needed to finish the job, as well as the amount of iterations it took
* use JavaScript to get the job done

What do you say?

**Comment by jumper320** [comment]
Don't worry, I haven't forgotten. I did program something over the days, although it is very little and it could be more. Right now, I analyze some sorting algorithms, shell sort currently. I don't think I will have many problems with understanding concepts and code but my laziness will be. I am going home early today, so we won't meet until Friday. Be assured I don't have any questions currently and if I have, I will first posting them here, before I ask you personally.

I want to work on my own without relying on you or Kriss to much. That means if you don't hear anything from me there is no problem. I will post ( or I at least hope once in a while) the code which works here so you can track/see my progress. My laziness and my procrastination were my problems in school and are my problems now and I try to tackle both of them while doing this little project. But if you want to meet me to talk about the current state then by all means ask.

I just want to shine a light on the current state, so you don't think I am doing absolutely nothing.

**Comment by k00ni** [comment]
Thanks for the insight. It is cool to see, that you take this seriously and i know you will overcome those two problems. Eager to see your results soon.

**Comment by k00ni** [comment]
Its basically the last week of July. Should i reserve some time for you this week? If not, when do you think can you present your results?

**Comment by jumper320** [comment]
No, you don't need to reserve time. To be frank I haven't done  anything further. I will be gone next on the 31th of  july for two weeks and will come back august 14th. I think we should stop the project since there is no progress from my side and I don't want to waste your time. If I do code, have questions related to programing or concepts, I will ask you. That way you don't have to have this project in the back in your mind.

I am sorry for the stop, but I need to solve my laziness and lack of motivation first before resuming any project. and wasting your time.
