### ISSUE TITLE
Learn basics of Github

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#3]
* [x] Register
* [x] What is a repository? (by @k00ni)
* [x] Basics of versioning and Git. (by @k00ni)

Bonus:
* [x] What are forks?
* [x] What is watching a repository?

**Comment by jumper320** [comment]
Grundlagen gelernt. @k00ni

**Comment by jumper320** [comment]
Register: A register is an index.

**Comment by jumper320** [comment]
Repository: A repository is a managed index for the retention and description of digital objects for a digital archive.

**Comment by jumper320** [comment]
I hope I got the essence and can cover the topic.

Basics of versioning and Git:

Git is a Distributed Version Control System (DVCS)

If a client wants to edit a file, he will not only download the file, he will mirror the whole repository. So when the repository is lost on the server, the client can restore it. So once files are committed to the repository, they are very difficult to loose.

Instead of file based changes the programmer will create a snapshot, a "copy", of the mini file system. That way he creates versions which can be compared.

Nearly every operation is local, therefore operations can be relatively quickly executed and it can be worked offline.

**Comment by jumper320** [comment]
What are forks?

A fork is a copy of a repository. Forking a repository allows you to freely experiment with changes without affecting the original project.

**Comment by jumper320** [comment]
What is watching a repository?

If you watch a repository, you'll be notified of all changes/conversations which will occur there.
