### ISSUE TITLE
Commands, functions and programs

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#4]
* [x] What is a command? 
* [x] What is a function? 
* [x] What is a program? 
* [x] Whats the difference between them?

Bonus: 
* [x] Are terms software, application and program the same?

**Comment by jumper320** [comment]
What is a command?

A command is a specific instruction given to a computer application to perform some kind of task or function.

**Comment by jumper320** [comment]
What is a function?

A function is a group of instructions, also known as a named procedure, used by programming languages to return a single result or a set of results.

**Comment by jumper320** [comment]
What is a program?

A program is a specific set of ordered operations for a computer to perform. In the modern computer that John von Neumann outlined in 1945, the program contains a one-at-a-time sequence of instructions that the computer follows.

**Comment by jumper320** [comment]
What is the difference between them?

A command is a specific instruction. A function is a group of instructions, also known as procedure. A program is a specific set of ordered operations for  computer to perform.

**Comment by jumper320** [comment]
What is the difference between them?

Computer software is all information processed by the computer systems, programs and data.

An application is a program with a specific application for the user.

So a program can be an application, but is always a part of the software.

**Comment by k00ni** [comment]
**Bonus:** Do you know what "call by reference" and "call by value" for function parameters means? And can you tell me, what the difference is?

**Comment by jumper320** [comment]
Call by Value

While passing parameters using call by value, a copy of the original parameter is created and passed to the called function.

Call by Reference/Pointer/Address 

While passing parameters using call by reference, we are passing the actual memory address/pointer of the variable to the called function.

Difference:

Using call by value won't affect the original value of the variable, due to the created copy. Using call by reference will affect the original value of the variable, thanks to referencing the memory address of the variable.
